### PR TITLE
typecheck: store resolved type of expr.TypeAssert in expression

### PR DESCRIPTION
**Pull request by sbinet**
Fixes neugram/ng#97.

### CODE REVIEW

**Comment by sbinet** [comment]
I must say I am not completely confident this is the right fix.
it seems like an _ad hoc_ one.

I tried to modify the `typecheck`er instead (replacing the `e.Type` value with the resolved value `t`, just before https://github.com/neugram/ng/blob/599d4a98c88e8f155107b525ac67273f77698da2/typecheck/typecheck.go#L2248 and after we checked we correctly resolved the type)
but this led to an infinite recursion.

**Comment by crawshaw** [comment]
This isn't right. No Unresolved type should survive type checking unless an error is produced. What change did you make to the type checker that caused an infinite loop? I can try unpicking it if you like.

**Comment by crawshaw** [comment]
I've been looking at this, and there is at least one other serious recursion problem in the type resolver. I'm going to have a go at that one, and hope something similar can be done for this.

**Comment by crawshaw** [comment]
OK, 0927fa8 should fix the infinite recursion during type resolution. Try dealing with the extra Unresolved in the type checker now.

**Comment by sbinet** [comment]
aaah... :)
I couldn't figure out why my simple change was working now :)

PTAL.

**Pull request merged**
