### PR TITLE
Check dup decl

### PR DESCRIPTION
**Pull request by sbinet**
Fixes neugram/ng#30.

### CODE REVIEW

**Comment by sbinet** [comment]
it still fails on `eval/testdata/import3.ng`:

```
$> go test ./eval
--- FAIL: TestPrograms (8.87s)
	eval_test.go:209: testdata/import3.ng:10: typecheck: no new variables on left side of :=
FAIL
```

ie: there:

```go
import "./vec.ng"

ok := vec.OK

if vec.X != "initx" {
	ok = false
	printf(`vec.X=%q, want %q`, vec.X, "initx")
}

X := "badx" // should be ignroed        // THERE <<<

prefix := "pass through: "
vec.X = prefix
want := prefix + "val"
if got := vec.PassThrough("val"); got != want {
	ok = false
	printf(`vec.PassThrough("val")=%q, want %q`, got, want)
}

if ok {
	print("OK")
}
```

it seems that when importing `vec.ng`, the `X` variable is being put inside the scope of the package importing `vec.ng`.
with a bit of "print foo"-fu, I convinced myself this didn't happen during the `checkImport` method but sometime after that.
I don't know yet enough of the callgraph to know where that could happen.

any idea?

**Comment by crawshaw** [comment]
Something is quite broken. The following type checks, it shouldn't:

```
import "./vec.ng"

print(X)
```

I'm looking into it.

**Comment by crawshaw** [comment]
OK the underlying problem should be fixed in f8543dc, thanks for catching that. Try a rebase and see if your tests pass now.

**Comment by sbinet** [comment]
PTAL.

I am not sure whether this is correct under `ng`, but I have made the executive decision that this:

```
import "fmt"
fmt := 42
```
isn't considered a redeclaration.

you may disagree :)

**Pull request merged**
