### PR TITLE
test export builtin

### PR DESCRIPTION
**Pull request by tmc**

### CODE REVIEW

**Comment by tmc** [comment]
@crawshaw I don't see why this is failing, would you mind taking a look?

```
~/go/src/neugram.io/ng(test-export)$ ng eval/testdata/export.ng
OK
```

**Comment by crawshaw** [comment]
An `*eval.Program` instance has an environment map. It is shared with the shell (a global, because the concept of shells don't fit into boxes inside processes, they are process global) by setting the global `shell.Env` to the same map. This is done in `ng.go`, but we are not doing it in the eval tests.

In fact, there's some setup logic for the environment in eval_test.go, but it never wires the shell and program together. Want to fix it?

The first thing I'd suggest is modifying eval.EvalFile so it takes an env map as an argument, and sets the program env map. (Aliases too!)

Then instead of setting up shell.Env once for the entire eval_test.go, do it for each subtest (so they are hermitic) and pass shell.Env after it's been replaced into EvalFile.

**Comment by crawshaw** [comment]
After some more thought, I believe we can do better than the shell state globals. I'm going to try and fix this.

**Comment by crawshaw** [comment]
OK this test should pass after 75b579a.

**Pull request merged**
